project:
  type: website

website:
  title: "fnands"
  site-url: https://fnands.com
  description: "My personal site"
  favicon: "assets/f_favicon.webp"
  navbar:
    left:
    # ğŸ  ğŸ“® ğŸ‘¨ğŸ½â€ğŸ’» ğŸ ğŸ¤ ğŸ“š
    - text: "Blog"
      href: index.qmd
    #- text: OSS
    #  file: oss/opensource.qmd
    #- text: Talks 
    #  file: talks.qmd
    - text: Notes
      file: notes/index.qmd
    - text: Talks
      file: talks/index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fnands
      - icon: twitter
        href: https://twitter.com/f_nan_d
      - icon: rss
        href: index.xml

format:
  html:
    reference-location: document
    code-fold: true
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true
    syntax-definitions: 
      - syntax/mojo_syntax.xml
      - syntax/julia.xml



